### PR TITLE
[Explore] Refresh chart overlay when chart is out of sync with control panel

### PR DESCRIPTION
**Pull request by gabe-lyons**
This is a follow up to https://github.com/apache/incubator-superset/pull/4459 to make it more obvious when the chart should be refreshed.

no changes looks like this:
image

after making a change affecting the query:
image

but if you make a change causing errors:
image

### CODE REVIEW

**Comment by michellethomas** [comment]
This is super cool!! 🎉 

I like the designs Chris had where the opacity is changed in the chart itself. What do you think of that instead of the dark overlay?

image

**Comment by john-bodley** [comment]
I second @michellethomas's comment regarding opacity.

**Comment by gabe-lyons** [comment]
@michellethomas @john-bodley Sounds good to me 👍 I'll make that change

**Comment by gabe-lyons** [comment]
cc @michellethomas @john-bodley updated overlay to cause the graph to fade out a bit.

**Comment by michellethomas** [comment]
this looks really good 🎉

**Pull request closed without merging**
